name: Slash Command Routing
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@e1b4e266bc781656359bb7e462e228daf68c04f6 # v5.0.0
        with:
          token: ${{ secrets.SBR_BOT_TOKEN }}
          config: >
            [
              {
                "command": "retest",
                "permission": "write",
                "issue_type": "pull-request",
                "repository": "shortbrain/workflows-experiments"
              },
              {
                "command": "build",
                "permission": "write",
                "issue_type": "pull-request",
                "repository": "shortbrain/workflows-experiments"
              },
              {
                "command": "cherry-pick",
                "permission": "write",
                "issue_type": "pull-request",
                "repository": "shortbrain/workflows-experiments"
              }
            ]
